### ISSUE TITLE
Submit a Story Page - v1

### ISSUE THREAD

**Issue by RookieOne** [RookieOne/phoenix-lobsters#34]
Route is `/stories/new`

You have to be signed in to get to this page
Form fields
- url: optional
- title: required
- description: optional

Submit button should create story and redirect user to the Story Discussion Page

**Comment by crertel** [comment]
This work is being done in branch `add_story_submission`.

**Comment by crertel** [comment]
So, I've got this working now.

I've also got it wired up to convert the description markdown into html. :)

I noticed that when creating a story it dropped us back to the index, so I made it redirect to the story page.

On a related note, I made a story page.

**Comment by crertel** [comment]
This had also got it fixed up so that the server story submission time is stamped.

**Comment by crertel** [comment]
I'd like to go ahead and get this merged @RookieOne so I can do the cleanup on the lobster -> lobsters thing.

Can we make another issue to harden this work and add tests?
